"use client";

import Link from "next/link";
import { ArrowDown, ArrowLeft, ArrowUpRight, Check } from "lucide-react";
import { motion } from "motion/react";
import { SiteHeader } from "@/components/layout/site-header";
import type { DesignPartnershipService } from "@/data/services";

const t = { duration: 0.65, ease: [0.16, 1, 0.3, 1] as const };
const flow = [{ number: "01", title: "需求了解", description: "了解企业业务和设计需求。" }, { number: "02", title: "合作规划", description: "制定长期支持方式。" }, { number: "03", title: "持续交付", description: "按阶段完成设计任务。" }, { number: "04", title: "优化升级", description: "根据企业发展持续调整。" }] as const;
type P = { service: DesignPartnershipService };
export function DesignPartnershipDetail({ service }: P) { return <main className="bg-obsidian"><SiteHeader /><Hero service={service} /><Light label="BUSINESS VALUE" title="为什么企业需要长期设计合作" items={service.valuePoints} /><Scope service={service} /><Light label="WHO IT IS FOR" title="适合哪些企业" items={service.customerTypes} /><Flow /><Light label="COOPERATION MODEL" title="灵活合作方式" items={service.cooperationModes} /><CTA /></main>; }
function Hero({ service }: P) { return <section id="top" className="relative isolate overflow-hidden bg-obsidian text-text-primary"><div aria-hidden className="absolute inset-0 bg-[radial-gradient(circle_at_80%_34%,rgba(124,58,237,0.14),transparent_26%),radial-gradient(circle_at_68%_76%,rgba(255,107,74,0.08),transparent_24%)]" /><div aria-hidden className="absolute right-0 top-0 h-full w-[50%] opacity-25 [background-image:linear-gradient(rgba(255,255,255,0.055)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.055)_1px,transparent_1px)] [background-size:44px_44px] [mask-image:linear-gradient(to_left,black,transparent)]" /><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={t} className="relative mx-auto flex min-h-[74svh] max-w-[1280px] flex-col justify-end px-5 pb-16 pt-32 sm:px-8 sm:pb-20 sm:pt-40 lg:px-12 lg:pb-24"><Link href="/services" className="mb-12 inline-flex min-h-11 w-fit items-center gap-2 text-[12px] text-text-secondary"><ArrowLeft size={15} />返回服务列表</Link><p className="text-[11px] font-medium tracking-[0.16em] text-text-secondary">SERVICE</p><p className="mt-4 text-[11px] font-medium tracking-[0.16em] text-text-secondary">{service.englishTitle}</p><h1 className="mt-6 text-balance text-[clamp(3rem,6vw,6.1rem)] font-normal leading-[1.02] tracking-[-0.065em]">{service.title}</h1><p className="mt-8 max-w-[620px] text-[17px] leading-8 text-text-secondary sm:text-lg">{service.description}</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/contact" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-button bg-soft-white px-5 text-sm font-medium text-obsidian">获取合作方案<ArrowUpRight size={16} /></Link><Link href="/services" className="inline-flex min-h-12 items-center justify-center rounded-button border border-white/20 px-5 text-sm font-medium">返回服务列表</Link></div></motion.div></section>; }
function Light({ label, title, items }: { label: string; title: string; items: readonly { title: string; description: string; number?: string }[] }) { return <section className="bg-background-light text-text-primary-on-light"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 sm:py-28 lg:px-12 lg:py-32"><Head label={label} title={title} light /><div className="mt-10 grid gap-3 lg:mt-12 lg:grid-cols-3">{items.map((x, i) => <motion.article key={x.title} initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.18 }} transition={{ ...t, delay: i * .08 }} className="min-h-[190px] rounded-card border border-black/10 bg-white p-6 transition duration-300 hover:-translate-y-1 hover:border-black/20 hover:shadow-[0_16px_36px_rgba(16,16,18,0.07)] sm:p-7"><span className="text-sm text-text-tertiary-on-light">{x.number ?? `0${i + 1}`}</span><h3 className="mt-8 text-[23px] font-medium tracking-[-.04em]">{x.title}</h3><p className="mt-3 text-sm leading-6 text-text-secondary-on-light">{x.description}</p></motion.article>)}</div></div></section>; }
function Scope({ service }: P) { return <section className="bg-graphite text-text-primary"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 sm:py-28 lg:px-12 lg:py-32"><Head label="SERVICE SCOPE" title="长期支持范围" /><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:mt-12">{service.serviceItems.map((x, i) => <motion.article key={x.number} initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .18 }} transition={{ ...t, delay: i * .07 }} className="min-h-[220px] rounded-card border border-white/10 bg-white/[.04] p-6 transition duration-300 hover:-translate-y-1 hover:border-white/[.22] sm:p-7"><span className="text-sm text-text-tertiary">{x.number}</span><h3 className="mt-9 text-[24px] font-medium tracking-[-.04em]">{x.title}</h3><p className="mt-3 text-sm leading-6 text-text-secondary">{x.description}</p><div className="mt-6 flex flex-wrap gap-2">{x.keywords?.map(k => <span key={k} className="rounded-button border border-white/15 px-2.5 py-1 text-[9px] tracking-[.08em] text-text-tertiary">{k}</span>)}</div></motion.article>)}</div></div></section>; }
function Flow() { return <section className="bg-obsidian text-text-primary"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 sm:py-28 lg:px-12 lg:py-32"><Head label="COOPERATION PROCESS" title="建立长期协作关系" /><div className="mt-10 grid gap-3 lg:mt-12 lg:grid-cols-4 lg:gap-0 lg:divide-x lg:divide-white/10">{flow.map((x, i) => <motion.article key={x.number} initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .18 }} transition={{ ...t, delay: i * .08 }} className="relative min-h-[210px] rounded-card border border-white/10 bg-white/[.025] p-6 sm:p-7 lg:rounded-none lg:border-y-0 lg:border-r-0 lg:border-l-0 lg:bg-transparent"><span className="text-sm text-text-tertiary">{x.number}</span><h3 className="mt-9 text-[22px] font-medium">{x.title}</h3><p className="mt-3 text-sm leading-6 text-text-secondary">{x.description}</p>{i < 3 && <ArrowDown size={15} className="absolute bottom-5 right-5 text-text-tertiary lg:hidden" />}</motion.article>)}</div></div></section>; }
function Head({ label, title, light = false }: { label: string; title: string; light?: boolean }) { return <motion.div initial={{ opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }} transition={t} className={`border-b pb-12 lg:pb-16 ${light ? "border-black/10" : "border-white/10"}`}><p className={`text-[11px] font-medium tracking-[.16em] ${light ? "text-text-secondary-on-light" : "text-text-secondary"}`}>{label}</p><h2 className="mt-6 text-balance text-[clamp(2.25rem,4vw,4.25rem)] font-normal leading-[1.08] tracking-[-.055em]">{title}</h2></motion.div>; }
function CTA() { return <section className="bg-obsidian text-text-primary"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 sm:py-28 lg:px-12 lg:py-32"><div className="rounded-section border border-white/10 bg-[radial-gradient(circle_at_84%_18%,rgba(124,58,237,.17),transparent_28%),linear-gradient(130deg,#151518,#0a0a0b)] p-7 sm:p-10 lg:flex lg:items-end lg:justify-between lg:p-14"><div className="max-w-[700px]"><p className="text-[11px] font-medium tracking-[.16em] text-text-secondary">BUSINESS INQUIRY</p><h2 className="mt-6 text-balance text-[clamp(2.25rem,4vw,4.25rem)] font-normal">建立稳定的企业设计协作关系</h2><div className="mt-7 flex flex-wrap gap-x-5 gap-y-3 text-sm text-text-secondary"><span className="inline-flex items-center gap-2"><Check size={14} className="text-signal-violet" />长期支持</span><span className="inline-flex items-center gap-2"><Check size={14} className="text-signal-violet" />合同合作</span></div></div><Link href="/contact" className="mt-8 inline-flex min-h-12 items-center justify-center gap-2 rounded-button bg-soft-white px-5 text-sm font-medium text-obsidian lg:mt-0">商务合作<ArrowUpRight size={16} /></Link></div></div></section>; }
