"use client";

import Link from "next/link";
import { ArrowDown, ArrowLeft, ArrowUpRight, Check } from "lucide-react";
import { motion } from "motion/react";
import { SiteHeader } from "@/components/layout/site-header";
import type { EcommerceVisualService } from "@/data/services";

const transition = { duration: 0.65, ease: [0.16, 1, 0.3, 1] as const };
const process = [
  { number: "01", title: "需求沟通", description: "了解产品特点和商业目标。" },
  { number: "02", title: "视觉规划", description: "确定产品展示方向。" },
  { number: "03", title: "设计制作", description: "完成视觉内容开发。" },
  { number: "04", title: "优化交付", description: "持续调整并完成交付。" },
] as const;
type Props = { service: EcommerceVisualService };

export function EcommerceVisualDetail({ service }: Props) { return <main className="bg-obsidian"><SiteHeader /><Hero service={service} /><Values service={service} /><Scope service={service} /><Customers service={service} /><Process /><Modes service={service} /><CTA /></main>; }
function Hero({ service }: Props) { return <section id="top" className="relative isolate overflow-hidden bg-obsidian text-text-primary"><div aria-hidden="true" className="absolute inset-0 bg-[radial-gradient(circle_at_80%_34%,rgba(124,58,237,0.13),transparent_26%),radial-gradient(circle_at_68%_76%,rgba(255,107,74,0.08),transparent_24%)]" /><div aria-hidden="true" className="absolute right-0 top-0 h-full w-[50%] opacity-25 [background-image:linear-gradient(rgba(255,255,255,0.055)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.055)_1px,transparent_1px)] [background-size:44px_44px] [mask-image:linear-gradient(to_left,black,transparent)]" /><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={transition} className="relative mx-auto flex min-h-[74svh] max-w-[1280px] flex-col justify-end px-5 pb-16 pt-32 sm:px-8 sm:pb-20 sm:pt-40 lg:px-12 lg:pb-24"><Link href="/services" className="mb-12 inline-flex min-h-11 w-fit items-center gap-2 text-[12px] text-text-secondary"><ArrowLeft size={15} />返回服务列表</Link><p className="text-[11px] font-medium tracking-[0.16em] text-text-secondary">SERVICE</p><p className="mt-4 text-[11px] font-medium tracking-[0.16em] text-text-secondary">{service.englishTitle}</p><h1 className="mt-6 text-balance text-[clamp(3rem,6vw,6.1rem)] font-normal leading-[1.02] tracking-[-0.065em]">{service.title}</h1><p className="mt-8 max-w-[620px] text-[17px] leading-8 text-text-secondary sm:text-lg">{service.description}</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/contact" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-button bg-soft-white px-5 text-sm font-medium text-obsidian transition duration-300 hover:-translate-y-0.5">获取定制方案<ArrowUpRight size={16} /></Link><Link href="/services" className="inline-flex min-h-12 items-center justify-center rounded-button border border-white/20 px-5 text-sm font-medium text-text-primary">返回服务列表</Link></div></motion.div></section>; }
function Values({ service }: Props) { return <LightSection label="BUSINESS VALUE" title="为什么企业需要电商视觉优化">{service.valuePoints.map((item, i) => <LightCard key={item.number} index={i}><span className="text-sm text-text-tertiary-on-light">{item.number}</span><h3 className="mt-10 text-[26px] font-medium tracking-[-0.04em]">{item.title}</h3><p className="mt-3 text-sm leading-6 text-text-secondary-on-light">{item.description}</p></LightCard>)}</LightSection>; }
function Scope({ service }: Props) { return <section className="bg-graphite text-text-primary"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 sm:py-28 lg:px-12 lg:py-32"><Heading label="SERVICE SCOPE" title="服务内容" /><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:mt-12">{service.serviceItems.map((item, i) => <motion.article key={item.number} initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.18 }} transition={{ ...transition, delay: i * 0.07 }} className="min-h-[220px] rounded-card border border-white/10 bg-white/[0.04] p-6 transition duration-300 hover:-translate-y-1 hover:border-white/[0.22] sm:p-7"><span className="text-sm text-text-tertiary">{item.number}</span><h3 className="mt-9 text-[24px] font-medium tracking-[-0.04em]">{item.title}</h3><p className="mt-3 text-sm leading-6 text-text-secondary">{item.description}</p><div className="mt-6 flex flex-wrap gap-2">{item.keywords?.map((tag) => <span key={tag} className="rounded-button border border-white/15 px-2.5 py-1 text-[9px] tracking-[0.08em] text-text-tertiary">{tag}</span>)}</div></motion.article>)}</div></div></section>; }
function Customers({ service }: Props) { return <LightSection label="WHO IT IS FOR" title="适合哪些企业">{service.customerTypes.map((item, i) => <LightCard key={item.title} index={i}><span className="text-sm text-text-tertiary-on-light">0{i + 1}</span><h3 className="mt-8 text-[23px] font-medium tracking-[-0.04em]">{item.title}</h3><p className="mt-3 text-sm leading-6 text-text-secondary-on-light">{item.description}</p></LightCard>)}</LightSection>; }
function Process() { return <section className="bg-obsidian text-text-primary"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 sm:py-28 lg:px-12 lg:py-32"><Heading label="COOPERATION PROCESS" title="从产品理解，到视觉呈现" /><div className="mt-10 grid gap-3 lg:mt-12 lg:grid-cols-4 lg:gap-0 lg:divide-x lg:divide-white/10">{process.map((item, i) => <motion.article key={item.number} initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.18 }} transition={{ ...transition, delay: i * 0.08 }} className="relative min-h-[210px] rounded-card border border-white/10 bg-white/[0.025] p-6 sm:p-7 lg:rounded-none lg:border-y-0 lg:border-r-0 lg:border-l-0 lg:bg-transparent"><span className="text-sm text-text-tertiary">{item.number}</span><h3 className="mt-9 text-[22px] font-medium tracking-[-0.04em]">{item.title}</h3><p className="mt-3 text-sm leading-6 text-text-secondary">{item.description}</p>{i < 3 && <ArrowDown size={15} className="absolute bottom-5 right-5 text-text-tertiary lg:hidden" />}</motion.article>)}</div></div></section>; }
function Modes({ service }: Props) { return <LightSection label="COOPERATION MODEL" title="灵活合作方式">{service.cooperationModes.map((item, i) => <LightCard key={item.title} index={i}><span className="text-sm text-text-tertiary-on-light">0{i + 1}</span><h3 className="mt-8 text-[23px] font-medium tracking-[-0.04em]">{item.title}</h3><p className="mt-3 text-sm leading-6 text-text-secondary-on-light">{item.description}</p></LightCard>)}</LightSection>; }
function CTA() { return <section className="bg-obsidian text-text-primary"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 sm:py-28 lg:px-12 lg:py-32"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.2 }} transition={transition} className="rounded-section border border-white/10 bg-[radial-gradient(circle_at_84%_18%,rgba(124,58,237,0.17),transparent_28%),linear-gradient(130deg,#151518,#0a0a0b)] p-7 sm:p-10 lg:flex lg:items-end lg:justify-between lg:p-14"><div className="max-w-[700px]"><p className="text-[11px] font-medium tracking-[0.16em] text-text-secondary">BUSINESS INQUIRY</p><h2 className="mt-6 text-balance text-[clamp(2.25rem,4vw,4.25rem)] font-normal leading-[1.08] tracking-[-0.055em]">让产品信息，更清晰地在线上呈现</h2><div className="mt-7 flex flex-wrap gap-x-5 gap-y-3 text-sm text-text-secondary"><span className="inline-flex items-center gap-2"><Check size={14} className="text-signal-violet" />支持项目合作</span><span className="inline-flex items-center gap-2"><Check size={14} className="text-signal-violet" />支持长期视觉支持</span></div></div><Link href="/contact" className="mt-8 inline-flex min-h-12 items-center justify-center gap-2 rounded-button bg-soft-white px-5 text-sm font-medium text-obsidian lg:mt-0">商务合作<ArrowUpRight size={16} /></Link></motion.div></div></section>; }
function Heading({ label, title }: { label: string; title: string }) { return <motion.div initial={{ opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.2 }} transition={transition} className="border-b border-white/10 pb-12 lg:pb-16"><p className="text-[11px] font-medium tracking-[0.16em] text-text-secondary">{label}</p><h2 className="mt-6 text-balance text-[clamp(2.25rem,4vw,4.25rem)] font-normal leading-[1.08] tracking-[-0.055em]">{title}</h2></motion.div>; }
function LightSection({ label, title, children }: { label: string; title: string; children: React.ReactNode }) { return <section className="bg-background-light text-text-primary-on-light"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 sm:py-28 lg:px-12 lg:py-32"><motion.div initial={{ opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.2 }} transition={transition} className="border-b border-black/10 pb-12 lg:pb-16"><p className="text-[11px] font-medium tracking-[0.16em] text-text-secondary-on-light">{label}</p><h2 className="mt-6 text-balance text-[clamp(2.25rem,4vw,4.25rem)] font-normal leading-[1.08] tracking-[-0.055em]">{title}</h2></motion.div><div className="mt-10 grid gap-3 lg:mt-12 lg:grid-cols-3">{children}</div></div></section>; }
function LightCard({ children, index }: { children: React.ReactNode; index: number }) { return <motion.article initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.18 }} transition={{ ...transition, delay: index * 0.08 }} className="min-h-[190px] rounded-card border border-black/10 bg-white p-6 transition duration-300 hover:-translate-y-1 hover:border-black/20 hover:shadow-[0_16px_36px_rgba(16,16,18,0.07)] sm:p-7">{children}</motion.article>; }
