"use client";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { motion } from "motion/react";
import { aboutDirections, aboutValues } from "@/data/about";
import { siteCompany } from "@/data/site";
const t = { duration: .65, ease: [0.16, 1, .3, 1] as const };
function Head({ label, title, light=false }: {label:string;title:string;light?:boolean}) { return <motion.div initial={{opacity:0,y:22}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={t} className={`border-b pb-12 lg:pb-16 ${light?'border-black/10':'border-white/10'}`}><p className={`text-[11px] font-medium tracking-[.16em] ${light?'text-text-secondary-on-light':'text-text-secondary'}`}>{label}</p><h2 className="mt-6 text-balance text-[clamp(2.25rem,4vw,4.25rem)] font-normal leading-[1.08] tracking-[-.055em]">{title}</h2></motion.div>; }
export function AboutIntro(){return <section className="bg-background-light text-text-primary-on-light"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 sm:py-28 lg:px-12 lg:py-32"><Head light label="WHO WE ARE" title="从设计服务出发，面向企业未来发展"/><div className="mt-10 grid gap-8 lg:mt-12 lg:grid-cols-12"><div className="space-y-6 text-[16px] leading-8 text-text-secondary-on-light lg:col-span-8"><p>{siteCompany.shortName}专注企业品牌视觉建设、商业传播、电商视觉与数字内容设计，围绕企业真实需求提供系统化视觉支持。</p><p>在持续交付设计价值的同时，我们关注 AI 技术在内容生产、设计协作和企业服务中的应用，探索更高效、更灵活的工作方式。</p></div><div className="flex flex-wrap content-start gap-2 lg:col-span-4">{["企业设计服务","长期协作支持","AI 应用探索"].map(x=><span key={x} className="rounded-button border border-black/10 px-3 py-2 text-[11px] text-text-secondary-on-light">{x}</span>)}</div></div></div></section>}
export function AboutDirection(){return <section className="bg-graphite text-text-primary"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 sm:py-28 lg:px-12 lg:py-32"><Head label="OUR DIRECTION" title="设计能力与未来探索"/><div className="mt-10 grid gap-3 lg:mt-12 lg:grid-cols-3">{aboutDirections.map((x,i)=><motion.article key={x.number} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.18}} transition={{...t,delay:i*.08}} className="min-h-[250px] rounded-card border border-white/10 bg-white/[.04] p-6 transition duration-300 hover:-translate-y-1 hover:border-white/[.22] sm:p-7"><span className="text-sm text-text-tertiary">{x.number}</span><p className="mt-8 text-[10px] font-medium tracking-[.13em] text-text-secondary">{x.label}</p><h3 className="mt-3 text-[23px] font-medium">{x.title}</h3><p className="mt-3 text-sm leading-6 text-text-secondary">{x.description}</p><div className="mt-6 flex flex-wrap gap-2">{x.tags.map(y=><span key={y} className="rounded-button border border-white/15 px-2 py-1 text-[9px] text-text-tertiary">{y}</span>)}</div></motion.article>)}</div></div></section>}
export function AboutValue(){return <section className="bg-background-light text-text-primary-on-light"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 sm:py-28 lg:px-12 lg:py-32"><Head light label="HOW WE CREATE VALUE" title="我们如何创造价值"/><div className="mt-10 grid gap-3 lg:mt-12 lg:grid-cols-3">{aboutValues.map((x,i)=><motion.article key={x.number} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.18}} transition={{...t,delay:i*.08}} className="min-h-[190px] rounded-card border border-black/10 bg-white p-6 transition duration-300 hover:-translate-y-1 hover:border-black/20 sm:p-7"><span className="text-sm text-text-tertiary-on-light">{x.number}</span><h3 className="mt-8 text-[23px] font-medium">{x.title}</h3><p className="mt-3 text-sm leading-6 text-text-secondary-on-light">{x.description}</p></motion.article>)}</div></div></section>}
export function AboutPartnership(){return <section className="bg-obsidian text-text-primary"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 sm:py-28 lg:px-12 lg:py-32"><Head label="LONG-TERM PARTNERSHIP" title="成为企业长期伙伴"/><div className="mt-10 grid gap-8 lg:mt-12 lg:grid-cols-12"><div className="lg:col-span-8"><p className="text-[clamp(1.6rem,3vw,2.5rem)] leading-[1.2] tracking-[-.04em]">设计解决当下表达，AI 探索未来效率。</p><p className="mt-6 max-w-[680px] text-[16px] leading-8 text-text-secondary">{siteCompany.shortName}希望成为企业发展过程中的长期设计与创新协作伙伴，通过项目合作、持续设计支持和合同制服务，为企业提供稳定、灵活的视觉能力。</p></div><div className="flex flex-wrap content-start gap-2 lg:col-span-4">{["项目合作","长期设计支持","合同制合作"].map(x=><span key={x} className="rounded-button border border-white/15 px-3 py-2 text-[11px] text-text-secondary">{x}</span>)}</div></div></div></section>}
export function AboutCTA(){return <section className="bg-graphite text-text-primary"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 sm:py-28 lg:px-12 lg:py-32"><motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={t} className="rounded-section border border-white/10 bg-[radial-gradient(circle_at_84%_18%,rgba(124,58,237,.16),transparent_28%),#17171b] p-7 sm:p-10 lg:flex lg:items-end lg:justify-between lg:p-14"><div className="max-w-[720px]"><p className="text-[11px] font-medium tracking-[.16em] text-text-secondary">START A CONVERSATION</p><h2 className="mt-6 text-balance text-[clamp(2.25rem,4vw,4.25rem)] font-normal">开始一次合作交流</h2><p className="mt-6 text-[16px] leading-7 text-text-secondary">无论是企业品牌建设、商业传播、电商视觉、长期设计合作，还是对 AI 应用方向的交流，欢迎与{siteCompany.shortName}建立联系。</p></div><div className="mt-8 flex flex-wrap gap-3 lg:mt-0"><Link href="/contact" className="inline-flex min-h-12 items-center gap-2 rounded-button bg-soft-white px-5 text-sm font-medium text-obsidian">商务合作<ArrowUpRight size={16}/></Link><Link href="/services" className="inline-flex min-h-12 items-center rounded-button border border-white/20 px-5 text-sm font-medium">了解服务</Link></div></motion.div></div></section>}
